### ISSUE TITLE
Documentation "Recommended Way" load database configuration incorrect

### ISSUE THREAD

**Issue by semyon-san** [squareboat/nestjs-objection#2]
In the documentation in database.ts file you have:
`export default registerAs("db", () => ({`

but it won't work because "db" should be "database":
`export default registerAs("database", () => ({`

https://squareboat.com/open-source/nestjs-boilerplate/objection-setup#recommended-way

**Comment by vinayak25** [comment]
Thanks for reporting this. This is solved.
